version: "3.9"

networks:
  wasm:

services:
  app:
    build: .
    ports:
      - 9090:9090
    environment:
      - ASSETS_DIR=/app/assets
    networks:
      - wasm

  staging:
    build:
      dockerfile: Dockerfile.environments
    volumes:
      - ./environments/staging:/usr/local/apache2/htdocs/
      - ./bin/setup-project.sh:/usr/local/bin/setup-project.sh
    ports:
      - 9091:80
    networks:
      - wasm

  production:
    build:
      dockerfile: Dockerfile.environments
    volumes:
      - ./environments/production:/usr/local/apache2/htdocs/
      - ./bin/setup-project.sh:/usr/local/bin/setup-project.sh
    ports:
      - 9096:80
    networks:
      - wasm
